pipeline {
    agent any
    stages {
        stage('Plugin') {
            steps {
                lambdaTestRunner command: './mvnw test -Dtest=SmokeTest -Dmaven.repo.local=${MAVEN_USER_HOME}', functionName: 'LambdaTestRunner', s3Bucket: 'automatictester.co.uk-lambda-test-runner-build-outputs', region: 'eu-west-2', repoUri: 'https://github.com/automatictester/lambda-test-runner.git', storeToS3: 'target/surefire-reports'
            }
        }
    }
}
